# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sakura-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter daisy sakura,$(TARGET_DEVICE)),)

endif
